name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install rustup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    - name: Build
      run: cargo build --verbose
    - name: Run clippy
      run: cargo clippy --verbose
    - name: Run rustfmt
      run: cargo fmt --check

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install rustup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Run tests
      run: cargo test --verbose --all-features --lib --release
    - name: Run doctests
      run: cargo test --verbose --all-features --doc

  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install rustup
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: miri
    - name: Install nextest
      run: cargo install cargo-nextest
    - name: Run miri on libtests
      run: cargo miri nextest run -j8
    - name: Run miri on doctests
      run: cargo miri test --doc
